#ifndef CONSTANTS
#define CONSTANTS

#define SERVER_PORT 15005
#define MAX_CLIENTS 10
#define SHARED_MEMORY_SIZE 1024

#define MESSAGE_TYPE_SIZE 4
#define MESSAGE_DATA_SIZE 2048
#define MESSAGE_CHKS_SIZE 32

#endif